### ISSUE TITLE
App needs better handling of unhandled errors. 

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#10]
We have known for some time that unhandled errors crash the application rather than just log and carry on. We really need to spend some time thinking about how we can stop the app from crashing when there is an error that is not expected.

**Comment by timotheeguerin** [comment]
Probably need to make use of this https://angular.io/docs/ts/latest/api/core/index/ErrorHandler-class.html

**Comment by ascobie** [comment]
This has been taken care of with Tim's changes around error handling.
