### ISSUE TITLE
Job schedule support

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchLabs#1008]
Job schedule support should include:
- [x] basic configuration of all job schedules (list, get)
- [x] job schedule actions [delete, enable, disable, terminate, etc]
- [x] job schedule create actions [create, clone, create job schedule for jobs]

**Comment by johnnyzhang82** [comment]
I sketch the UI of how it looks before implementation, feel free to leave any feedbacks.
![untitled](https://user-images.githubusercontent.com/26984399/35068899-5117e90e-fb8d-11e7-9149-bfc6f5a8da73.png)
