### ISSUE TITLE
BatchLabs behind proxy

### ISSUE THREAD

**Issue by edo003** [Azure/BatchLabs#1015]
Can Batch Labs work with a Proxy Server. Our internal policy is for applications to go via a proxy and not directly to Internet.

**Comment by timotheeguerin** [comment]
Hi, currently there is nothing special BatchLabs does to provide proxy settings. This is however something we should consider adding.

**Comment by timotheeguerin** [comment]
Hi, I have been investigating a bit the proxy situation. I have a build here that I think should work. I'll work on making a ui to pick the proxy settings if that works for you.

Can you try with this build and set `HTTP_PROXY` and `HTTPS_PROXY` environment variables with your proxy settings and let me know if that works for you.

https://batchapppackage.blob.core.windows.net/batchlabs-build/BatchLabs-0.12.0-win.zip?st=2018-01-23T15%3A44%3A00Z&se=2019-01-24T15%3A44%3A00Z&sp=rl&sv=2017-04-17&sr=b&sig=TXuVjGyLkjjBqkEz84Ox0UhfVG8UH4Z3jf%2BnScsAVJ4%3D

If something doesn't work could you go to `%appdata%\batch-labs\logs\client.log` (on windows) or in  `Application Support/batch-labs/logs/client.log`(on osx)
