### ISSUE TITLE
File-group/container issue with adding more files

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1033]
-	Create empty "container" (e.g. “test”). Note: this is a container not a file group, so no "fgrp-" prefix.
-	Select container
-	“Add more files to the file group” (naming needs to set accordingly here)
-	Select folder to upload
-	Files are added to a new file group that’s created based on the same name as the original container (“fgrp-test”)

So the issue is that when you "add files to file group", its expecting it to be a file group not a container, so it's prefixing the container with "fgrp-" when it shouldn't (as it's a container not a file group). 

This UI needs to check if its uploading more files to a plain old container and if so, don't append the prefix.

**Comment by timotheeguerin** [comment]
I am disabling the button for non file group container. You can however still drag and drop files to add to it.
Other options is not to call the ncj library for adding files at all.
