### ISSUE TITLE
Storage Container Search Broken

### ISSUE THREAD

**Issue by psyrus** [Azure/BatchLabs#1039]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Description**
Upon updating to the new UI versions (>=0.12.xx), the ability to search in storage accounts (file groups) appears to be broken. Currently tested on 0.12.2, both the "All" and "File Groups" dropdown options do not yield any results when searching for partial/full file group names. The list simply stays in its unfiltered state. It was definitely working in previous (0.11.xx?) versions, as I used it often due to having over 100 file groups in my container.
**Instruction to repro the problem if applicable**
1. Open batch account in version 0.12.xx and above
2. Open data tab
3. Try to search for a partial/full container name
4. File group list will not be filtered

<img width="791" alt="bl-v12-fgrp-search" src="https://user-images.githubusercontent.com/8152287/35491415-bd1e806c-04e9-11e8-8fa0-7efffbd9a08e.png">

**Comment by ascobie** [comment]
Hi, i can see that indeed the filtering is broken. I think i can see what has happened. Should be a quick fix.
