### ISSUE TITLE
Updater appears to be broken

### ISSUE THREAD

**Issue by psyrus** [Azure/BatchLabs#1042]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Description**
The feature to update to the latest version of BatchLabs from within the interface appears to no longer work as of versions 0.12.xx. See video below for further description

https://www.youtube.com/watch?v=rDkg_V-UWz0

Edit: I just updated manually and noticed that both Windows Defender **and** my company's Symantec endpoint protection threw a fit when the installer was started. It may be related (being blocked only on my side).

**Comment by ascobie** [comment]
Hi Trevor, i can also confirm that 0.12.2 will not update to 0.12.3. 
Thanks for reporting this.

**Comment by timotheeguerin** [comment]
I think I fixed this problem, you will probably need to update manually to the next version.
