### ISSUE TITLE
Error redeem auth code for a token...

### ISSUE THREAD

**Issue by fbellgr** [Azure/BatchLabs#1044]
Every installations of the software on my windows 10 enterprise machines have stopped working a little over a week ago. The splashscreen never closes and the application does not load any account info after login.
I updated and even tried on 2 machines on which I had never used it.

In D:\Users\USER\AppData\Roaming\batch-labs\logs\client.log

I noticed the following line appearing after entering credentials:

{"name":"BatchLabs Main","hostname":"SNIP","pid":9752,"level":50,"msg":"Error redeem auth code for a token for resource https://management.core.windows.net/ URIError: URI malformed\n    at decodeURIComponent (<anonymous>)\n    at UserDecoder.base64DecodeStringUrlSafe (S:\\batch-labs-0.12.3-win\\resources\\app.asar\\src\\client\\core\\aad\\adal\\user-decoder.ts:53:16)\n    at UserDecoder.safeDecodeBase64 (S:\\batch-labs-0.12.3-win\\resources\\app.asar\\src\\client\\core\\aad\\adal\\user-decoder.ts:24:34)\n    at UserDecoder.decode (S:\\batch-labs-0.12.3-win\\resources\\app.asar\\src\\client\\core\\aad\\adal\\user-decoder.ts:13:35)\n    at AADService._processUserToken (S:\\batch-labs-0.12.3-win\\resources\\app.asar\\src\\client\\core\\aad\\adal\\aad.service.ts:211:40)\n    at AADService.<anonymous> (S:\\batch-labs-0.12.3-win\\resources\\app.asar\\src\\client\\core\\aad\\adal\\aad.service.ts:164:18)\n    at Generator.next (<anonymous>)\n    at fulfilled (S:\\batch-labs-0.12.3-win\\resources\\app.asar\\build\\client\\core\\aad\\adal\\aad.service.js:4:58)\n    at <anonymous>","time":"2018-01-30T23:19:09.143Z","v":0}

Hope something can be done relatively quickly, I've grown to rely on this thing.

Regard,

**Comment by ascobie** [comment]
Do you know what version you have installed? or is it the latest one 0.12.3?

**Comment by timotheeguerin** [comment]
Hi, 

can you try reverting to a previous version `https://github.com/Azure/BatchLabs/releases/tag/v0.11.0`

Also are you behind a proxy by any chances?

**Comment by fbellgr** [comment]
v0.11.0 works fine for me.
No proxy on any of my setups.

**Comment by timotheeguerin** [comment]
Hhm, the problem seems to be parsing your user token returned after authentication. Not sure what could be the problem, I'll take a look, can you keep using 0.11.0 in the meantime?

**Comment by fbellgr** [comment]
> can you keep using 0.11.0 in the meantime?

Sure. Thanks.

**Comment by timotheeguerin** [comment]
Hi, I think I might have found the 
problem. Can you try this build https://ci.appveyor.com/api/buildjobs/06j91ejr4auyypuv/artifacts/release%2FBatchLabs-0.12.3-win.zip

If that doesn't could you send the logs again? 

Thanks

**Comment by fbellgr** [comment]
You did it.
Thank you very much.

**Comment by timotheeguerin** [comment]
awesome!!, i'll push a new hotfix
