### ISSUE TITLE
Failed to extract account name from accountId

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/BatchLabs#1063]
**Description**
The BatchLabs is just hanging, no subscriptions are recognized The search procedure is pending.  
In the logs I see an error: Failed to extract account name from accountId

FYI, I have several subscriptions and put unused ones in the ignore-subscription list in settings.
I am running the app on Windows 10.

**Comment by timotheeguerin** [comment]
Hi,  could you share the logs of the application(Click profile > View logs > app.log and client.log).
You can send them to me directly tiguerin@microsoft.com

Is this an error that happened recently or it has never worked for you?

**Comment by lmiroslaw** [comment]
will do. The error happened to me during the last 2 days.

**Comment by timotheeguerin** [comment]
I'm looking at what this log means but it doesn't look like this could cause a crash.
Which version of BatchLabs are you using? Version `0.12.0` had a bug where it would not load the subscriptions. If you do could you try upgrading to `0.12.4`

**Comment by lmiroslaw** [comment]
With the new version everything seems to be ok.

**Comment by timotheeguerin** [comment]
Great to hear
