### ISSUE TITLE
Slow job search

### ISSUE THREAD

**Issue by javier-alvarez** [Azure/BatchLabs#1067]
I have an account with thousands of jobs and hundreds of tasks per job and the UI is very slow.

The filter search for jobs is very slow and almost unusable.

**Comment by timotheeguerin** [comment]
is the UI laggy(Freezes?) or it just takes a while to load data?

For the filter do you just mean the quick search box for jobs?

**Comment by javier-alvarez** [comment]
It is more when searching for data.

**Comment by timotheeguerin** [comment]
So you mean it takes quite a while to load the result of your search?
Is the azure portal faster?
