### ISSUE TITLE
Rerun task

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchLabs#108]
- [x] Rerun task with same setting (Reactivate api)
- [x] Rerun task width different settings(This needs to delete it and recreate it to keep the same id)

**Comment by itowlson** [comment]
Why implement this as delete-and-recreate rather than calling the reactivate API?  We did reactivate specifically to avoid the risk factors involved in 'delete and recreate' (and to have a common implementation that could be called from anywhere instead of being bound to a particular client).

**Comment by timotheeguerin** [comment]
Didn't know about this, will use that instead
