### ISSUE TITLE
Allow optional/empty fields in job/pool templates

### ISSUE THREAD

**Issue by psyrus** [Azure/BatchLabs#1082]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Description**
If a field is defined as a string in the template json file, the parameter can not be left empty. With render jobs, there will be times where users wish to override the settings in the scene file (such as the currently defined height & width for the frame, but there may be times where they wish to render with the settings contained in the scene files. 

Examples of things that would potentially be overridden:
- Resolution
- Output format
- Target render camera
- Output file depth
- Render layer selections
Edit: Here is a page for reference - https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/Maya/files/GUID-0280AB86-8ABE-4F75-B1B9-D5B7DBB7E25A-htm.html

This would probably necessitate a "required":"true" flag for fields, or something similar. 

In the screenshot below, the user wanted to override the output type to be EXR, but wished to not have to specifically define the camera (might involve opening up the scene and typing out a cryptically named camera name with a chance for a typo)... but leaving it blank to use the scene default is currently not possible (it seems).

<img width="859" alt="bl-custom-fields" src="https://user-images.githubusercontent.com/8152287/36530497-9114a988-17fe-11e8-830f-7db99e576b6d.png">

**Comment by timotheeguerin** [comment]
Can you try setting a default value to blank text, I think we got that problem earlier and we made it not required If default value is blank

**Comment by psyrus** [comment]
@timotheeguerin 

I assume you mean like this? It was like this from the start (when the first image above was captured)...
<img width="450" alt="bl-blank-default" src="https://user-images.githubusercontent.com/8152287/36581509-ab0dbb7e-18b0-11e8-80b4-913becc8c1a2.png">

**Comment by psyrus** [comment]
[maya-vray.txt](https://github.com/Azure/BatchLabs/files/1750698/maya-vray.txt)

I realized it's probably easier to clarify if i just upload the file. It's attached

**Comment by timotheeguerin** [comment]
hhm I'll take a look then, feel like we made this work some time ago might be a bug

**Comment by timotheeguerin** [comment]
After invesigating this seems to be a problem in the ncj cli. Made a PR there with a fix https://github.com/Azure/azure-batch-cli-extensions/pull/48

**Comment by psyrus** [comment]
Thanks for looking into that Tim! If I might make one final request/suggestion, would it be possible to have the "if the default string is set to empty string, the parameter is no longer required" functionality to be documented in the BatchLabs-data readme? 
https://github.com/Azure/BatchLabs-data

Otherwise it kind of ends up as one of those "hidden" features that if you know about, is very useful, if you don't, it may be a long path to discovery :)
