### ISSUE TITLE
Connect to Node - always says creds valid for 24 hours on node

### ISSUE THREAD

**Issue by smith1511** [Azure/BatchLabs#1085]
**Description**
Regardless of the time frame I select when creating a user to connect to a compute node, the following "Connect to node" screen always says 24 hours.

In the screenshot below I selected 30 days.

**Instruction to repro the problem if applicable**

![image](https://user-images.githubusercontent.com/1001494/36565616-19a022ca-1875-11e8-9350-2a24ec2747fe.png)

**Comment by timotheeguerin** [comment]
I think this is just a typo, can you double check the credentials are still working tomorrow
