### ISSUE TITLE
Auto storage errors going crazy in the console

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1154]
Clicking through accounts on the dashboard, if one i select doesn't have an auto-storage account set i see a large number of errors in the console. The main loading spinner stays spinning while all the errors are being reported, so it must be blocking something. Haven't noticed this before, it used to only log 1. Even then, it's a completed expected error so we probably shouldn't log it at all. 

e.g: after clearing the console i got 125 errors when clicking on: chaosgrouptest.westeurope.batch.azure.com

![capture](https://user-images.githubusercontent.com/10934358/37383176-e00681bc-27ab-11e8-93c6-a141e626f00e.PNG)

Also, this text overflows, so it's a CSS issue. 

![capture](https://user-images.githubusercontent.com/10934358/37383234-55aad86e-27ac-11e8-93db-08d7f3a93641.PNG)

**Comment by timotheeguerin** [comment]
![image](https://user-images.githubusercontent.com/1031227/37425835-0ea2e08a-2782-11e8-86f6-414cee31c74e.png)
For those errors

**Comment by ascobie** [comment]
Retries 125 times?

**Comment by timotheeguerin** [comment]
Only a few times but you probably clicked multiple accounts
