### ISSUE TITLE
Data not being disposed correctly when switching accounts

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1169]
Steps to repo: 
- Select account
- Delete a job with the job quick-list delete multiple button
- Select Dash then select **another** account
- Gets a 404 error for the job you just deleted in the **previous** account.

It's trying to load this job: 
https://andrewscus.southcentralus.batch.azure.com/jobs/07051eea-91c7-486b-a05f-a88aebd4c09c/tasks?api-version=2017-09-01.6.0&maxresults=25

But this job was created in the andrew1973 account ....

**Comment by timotheeguerin** [comment]
Doesn't seem to be because of the delete, just navigating to a job. Task list data is not disposed.

There is a few more like that are not disposed.
