### ISSUE TITLE
pool has no nodes. Rendering not started

### ISSUE THREAD

**Issue by rameezIkhan** [Azure/BatchLabs#1177]
Before submitting a bug please check the following:
- There is no similar bugs in the issue list.
- If you are building BatchLabs yourself please check you used `yarn install` instead of `npm install`

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

**Description**

**Instruction to repro the problem if applicable**

**Version of BatchLabs(For bugs)**

**Logs, for bugs(Click profile > View Logs > app.log, client.log)**

**Comment by timotheeguerin** [comment]
Hi, could you provide a bit more details on what is your issue?
What do you mean by rendering? 

Thanks

**Comment by rameezIkhan** [comment]
Hi, Job is active but it is showing on pools settings there no nodes are available.

Thanks



Rameez Khan
On Timothee Guerin <notifications@github.com>, 17-Mar-2018 7:19 PM wrote:

Hi, could you provide a bit more details on what is your issue?
What do you mean by rendering?

Thanks

**Comment by rameezIkhan** [comment]
I have provided a job using 3ds max with vray it's shows active as a in dashboard but no processes for rendering 3d files



Rameez Khan
On Timothee Guerin <notifications@github.com>, 17-Mar-2018 7:19 PM wrote:

Hi, could you provide a bit more details on what is your issue?
What do you mean by rendering?

Thanks

**Comment by timotheeguerin** [comment]
Is there any errors on the pool? Could you share a screen shot. Thanks

**Comment by ascobie** [comment]
Can you email rendering@microsoft.com and provide a job and pool ID for investigation. This issue is not related to batch labs. Someone will be able to help you out. Thanks, Andrew.

**Comment by ascobie** [comment]
Could you also.proveide a batch account ID. If a job is active and no tasks are being processed, that normally means there are either no nodes in the pool, or the nodes are there but didn't start correctly.

**Comment by rameezIkhan** [comment]
![batchlabs](https://user-images.githubusercontent.com/37472768/37579546-def0e6ca-2b64-11e8-9903-ac3a925203ad.JPG)
Hi Guys,
Attaching active jobs details for reference. I have selected pool and jobs it started process but stuck at 0% for hours

**Comment by ascobie** [comment]
Do you have a pool with nodes in it? The job will not be processed unless you have a pool with idle nodes

**Comment by ascobie** [comment]
The task is queued, so there are no available nodes in your pool to run the job on. Can you send a screenshot of the pool please.

**Comment by rameezIkhan** [comment]
Yes. In pools it showing "pool has no nodes". Attaching screen shot for your reference. Can you help me how to add nodes in pool.
![batchlabs_1](https://user-images.githubusercontent.com/37472768/37579752-1d10d996-2b66-11e8-8e75-82289276f257.JPG)

**Comment by ascobie** [comment]
Press the scale button below the pool name. 3rd button from the left that looks like an up and down arrow. You will get the scale form, scale the pool to 1 or more nodes. You may only need 1 as your job only has one task.  Dont forger to scale the pool down to 0 when you no longer need it.

**Comment by ascobie** [comment]
Oh I see it's an A8. That's a rather large vm to use for a test render. It does say resizing already. If it fails to resize you will need to file a support request.

**Comment by rameezIkhan** [comment]
It was resolved by changing pool region from southeastasia to uk south. Thanks for your support

**Comment by ascobie** [comment]
Ahh OK, glad it has resolved itself. The A8_v2 is a fairly new instance size and there may have been capacity issues in SE Asia. One of the bigger data-centers in UK or US should have plenty of them.

**Comment by ascobie** [comment]
Closing issue. Please email us at rendering@microsoft.com should you have any further rendering related issues. Thanks,
