### ISSUE TITLE
BatchLabs on Webapp

### ISSUE THREAD

**Issue by Ayanmullick** [Azure/BatchLabs#1178]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**Do I need to always run it from the desktop or is it possible to host BatchLabs on Azure Webapp? If yes, is there a walkthrough documentation for the same?**

**Instruction to repro the problem if applicable**
NA
**Version of BatchLabs(For bugs)**
NA
**Logs, for bugs(Click profile > View Logs > app.log, client.log)**
NA

**Comment by timotheeguerin** [comment]
Batchlabs is made using electron and depends on many of its features which prevent us to also deploy a website for it.

**Comment by timotheeguerin** [comment]
Electron is a framework that connect a browser environment with nodejs which give  much more functionalities than a regular website. So BatchLabs is indeed kind of a website but it needs to be loaded through electron. It will not work in a browser.
