### ISSUE TITLE
Rendering Output File

### ISSUE THREAD

**Issue by rameezIkhan** [Azure/BatchLabs#1183]
Before submitting a bug please check the following:
- There is no similar bugs in the issue list.
- If you are building BatchLabs yourself please check you used `yarn install` instead of `npm install`

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

**Description**

**Instruction to repro the problem if applicable**

**Version of BatchLabs(For bugs)**

**Logs, for bugs(Click profile > View Logs > app.log, client.log)**

**Comment by ascobie** [comment]
What seems to be the issue, you need to add the description of the issue in the body before submitting the issue.

**Comment by rameezIkhan** [comment]
Hi, I have rendered files through batchlabs after rendering is completed where can i find output files

**Comment by ascobie** [comment]
Did you use the "gallery" feature to submit the job? If so you must have selected an output file group to upload the output files to., you can see this storage container in the "Data" menu.

You can also click on the task from the job details page and you will be taken to the file explorer view of the node where the task was run. you will also see the stdout and stderr files. Note that you can only view files from here while the node is available. Once you scale down the pool you can only view your saved outputs in the "data" screen in the container where you uploaded the outputs to.

**Comment by rameezIkhan** [comment]
I have followed procedure but still i am unable to view my output files. If any documents is available kindly let me know

**Comment by ascobie** [comment]
Did the task complete correctly? Does it have a non-zero exit code? Did you look in the stdout and stderr files that you can see from clicking on the task? Did anything get uploaded to your file group that you selected when submitting the job? 

There are some docs here on submitting a 3ds max job: https://github.com/Azure/BatchLabs-data/tree/master/ncj/3dsmax

If you are having trouble getting your jobs to work, then this is NOT the place to raise issues. Please email rendering@microsoft.com and give all available information about what you are trying to do and someone will be able to help you.

thanks

**Comment by ascobie** [comment]
closing as customer is now in contact with rendering@microsoft.com
