### ISSUE TITLE
I cannot access a task after filtering

### ISSUE THREAD

**Issue by javier-alvarez** [Azure/BatchLabs#1207]
I cannot access a task after filtering. If I filter the tasks of a job by running. Clicking on a task doesnt open the task description panel. This is a major bug since I cannot access the logs of tasks after filtering them.

Without filtering I can click on task and acccess the task details.

Version
0.14.0

**Comment by timotheeguerin** [comment]
Hmm, I am able to reproduce. As a workaround for now you can click back on the filter icon when you selected a task and it will actually have the task selected. I'll take a look at fixing this

**Comment by timotheeguerin** [comment]
I have a fix for it. I'll wait a bit today before releasing 0.14.1 as there is a workaround just in case there is another issue coming up so we can bundle multiple fixes together. If you'd like the fix right now you can always download the artifact from appveyor(For windows) https://ci.appveyor.com/project/azure-batch/batchlabs/build/1.0.3303

**Comment by ascobie** [comment]
PR gone out and 14.1 released.
