### ISSUE TITLE
Add file extension support to file-in-file-group advanced type

### ISSUE THREAD

**Issue by smith1511** [Azure/BatchLabs#1209]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ x ] feature request

**Description**

Batch Labs implements its own NCJ 'advanced types' that allow you to do things like associate a parameter with a file-in-file-group.  It would be great if this could be extended to optionally specify a filename extension pattern.  I have various scenes where the root of the filegroup contains thousands of files and finding a scene file (and others) can be tricky.

Something like:

        "sceneFile": {
            "type": "string",
            "metadata": {
                "description": "The 3ds Max scene file to be rendered",
                "advancedType": "file-in-file-group",
                "dependsOn": "inputFilegroup",
                "filenameExtension":".max"
            }
        },

**Comment by timotheeguerin** [comment]
This sounds reasonable enough

**Comment by smith1511** [comment]
An additional feature in this area is to be able to search for filegroups in the selector as there can be many of them.

_... suggested that we have a search box in the file group selector also, as he has hundreds of containers and finds it tricky to find the correct container for the inputs and outputs._
