### ISSUE TITLE
bl-select always defaults to focusFirstOption()

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1258]
Select defined as: 
```
<bl-select placeholder="Filter" [ngModel]="pickedFilter" (ngModelChange)="pickSelectedFilter($event)">
    <bl-option *ngFor="let filter of optionFilters;trackBy:trackFilterOption"
        [label]="filter.label"
        [value]="filter.value">
    </bl-option>
</bl-select>
```

ngModel has the correct default value, but the fist option is always picked, even though when i open the picker, the correct item based on the model is selected.

![image](https://user-images.githubusercontent.com/10934358/38592953-13f86006-3d93-11e8-93e3-68b9484c8dce.png)

But opening the option list has the first item selected: 

![image](https://user-images.githubusercontent.com/10934358/38592975-3752edfa-3d93-11e8-9857-377135af4a12.png)

When it should be the one that matches the model.

**Comment by ascobie** [comment]
Update, setting the focused value in here fixes it, but not sure if this would have any flow on effects: 
```
    public writeValue(value: any): void {
        if (this.multiple) {
            this.selected = new Set(value);
        } else {
            this.selected = new Set(value ? [value] : []);
            **this.focusedOption = value;**
        }
        this.changeDetector.markForCheck();
    }
```

**Comment by timotheeguerin** [comment]
i have a branch with v2 of the select. Current version has a few issues when there is not enough space to display or the parent is overflow hidden.

 I'll update there.

**Comment by ascobie** [comment]
Cool, thanks. I'll revert the change I made.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
