### ISSUE TITLE
"Request Body" limit of 1048576

### ISSUE THREAD

**Issue by psyrus** [Azure/BatchLabs#1286]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Description**

As per the details of the job in #1285, I wrote a custom job template to run the render job contained in the file group with (which is apparently not 50,000 but 33,108 files) but upon submission, an error is displayed:
<img width="234" alt="files-limit" src="https://user-images.githubusercontent.com/8152287/38919086-8c6cbe6e-432a-11e8-971b-90b39238ba84.png">
> The request body is too large and exceeds the maximum permissible limit.
> MaxLimit: 1048576

This number is 2^20, which seems to be related to the previous 2^15 character limit on resource files from #978. 

Would I be correct in assuming that I will have to skip the resouceFiles directive and instead use AzCopy to get the resourceFiles onto the node as done below?
https://github.com/Azure/BatchLabs-data/blob/master/ncj/3dsmax/standard/job.template.json#L164

**Version of BatchLabs(For bugs)**
v0.14.1

**Comment by ascobie** [comment]
Yes, this is an annoying limit on Batch and the CLI and it catches us out daily. Are you using 3dsMax? We have a workaround that I can share with you. There are a couple of ways we can accomplish this.

Shortly we will be implementing the FUSE container adapter that just mounts the container in the server side do there is no need for resource files. We can also use a job preparation task to copy files onto the nodes first without having to include them as resource files.

I will probably need to wait until the morning to get this for you as I need to check with a workmate first.

Andrew


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ascobie** [comment]
That's fine, it should work with Maya as well. I mentioned 3ds max as it's already implemented for those templates.

If you can't wait until the morning then check out the 3ds max templates. Basically we pass a container sas to a PowerShell script and it downloads all the files from the job prep task onto the node.

If you like, email @Christian<mailto:Christian.Smith@microsoft.com> and he should be able to point you in the right direction.

Are you using the out of the box Maya templates? Or your own custom ones via batch labs?

Cheers

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by psyrus** [comment]
Using the following, I was able to get the job to submit successfully (with the supporting parameters added as well). 

`                "commandLine": "azcopy /source:\"[parameters('inputFilegroupSas')]\" /dest:\"%AZ_BATCH_JOB_PREP_WORKING_DIR%\\assets\" /S || exit /b %errorlevel% & exit /b 0",
`

All my templates are custom (Frankenstein's monster style) ones patched together by referring to the BatchLabs-data repo. 

Thanks for all your help.

**Comment by psyrus** [comment]
Since the workaround seems to work, I guess this issue can be closed. Up to you of course.

**Comment by smith1511** [comment]
@psyrus The FUSE container Andy mentions is support for mounting a Blob container using Blobfuse here: https://github.com/Azure/azure-storage-fuse

Essentially it would mount the Blob container locally and allow reading/writing in a similar manner to Azure Files/CIFS, however you get significant throughput advantages of Blob over Files.

This should be available shortly...

**Comment by ascobie** [comment]
Great stuff. Glad you managed to get it working! Will close for now as it's a known issue. They are looking to fix the CLI which will make it slightly better but Batch still has a resource files limit until server side file groups are implemented.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by psyrus** [comment]
@smith1511 Thanks for the explanation, Christian. 
This probably isn't the correct forum for an in depth discussion about it, but one thing (that I'm sure you're aware of already but I'll throw out there just in case) is that at least for the Maya & Arnold scenes that I've used, all referenced assets (textures, embedded scenes etc) are loaded into memory before the rendering starts, which means if every node in a batch pool is trying to hit a single blob container every time a new frame is rendered, it'll be a major bottleneck. 

I would recommend (and I assume it's being designed as such) is that after mounting, things are still copied to the job-prep-directory as it currently is. 

@ascobie Thanks for all the help!

**Comment by ascobie** [comment]
Closing this as its a known issue an we have a workaround while they sort out the server side niggles with Batch. Have forwarded your message to Christian in case he missed it here. 

Thanks.
