### ISSUE TITLE
Missing timestamp after generating credentials to connect to node

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/BatchLabs#1304]
**I'm submitting a ...**  (check one with "x")
[x] bug report

**Description**

After generating credentials for connecting directly to a compute node, the prompt seems to be missing a timestamp.

Actual:
![image](https://user-images.githubusercontent.com/1272094/39162806-6593ce36-47cb-11e8-8a0f-e8042c1fcf17.png)

Expected: "These credentials are now valid until {instant} on this node"

**Instruction to repro the problem if applicable**

Select a compute node and press the "plug" icon to connect
Press the "Generate" button on the sidebar and wait for credentials to be generated

**Version of BatchLabs(For bugs)**

Version 0.14.1 (Freshly downloaded)

**Comment by timotheeguerin** [comment]
Yeah seems like it only show the timestamp when you specify creds. Generate are empty
