### ISSUE TITLE
Spin control arrows should be closer to the value they modify

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/BatchLabs#1312]
**I'm submitting a ...**  (check one with "x")
[x] feature request

**Description**

When modifying the number of nodes in my pool, the arrows from the spin-controls are a long way from the value they modify - in fact, they're *much* closer to the adjacent value.

![image](https://user-images.githubusercontent.com/1272094/39338065-a71cc632-4a14-11e8-94b8-da8923ebc815.png)

The arrows and the number should be visually grouped together.

This could be achieved by:

* Right aligning the numbers within the field; or
* Showing the arrows at the lefthand side of the field; or
* Using a horizontally aligned spin control with buttons to the left and right of the value; or
* Something smart I haven't thought of. 😀 

**Sample Images**

![image](https://user-images.githubusercontent.com/1272094/39340297-7731e9fe-4a21-11e8-8cae-db73e1f76b3c.png)
![image](https://user-images.githubusercontent.com/1272094/39340314-8d131c34-4a21-11e8-8b39-392de80bb9f1.png)

And a hand drawn one ...

![image](https://user-images.githubusercontent.com/1272094/39340982-36a4060c-4a25-11e8-9d0b-5f994e8967e5.png)

**Comment by ascobie** [comment]
As this is a material UI control, it may be that the effort required to change it outweighs the benefits. I would be all for just removing the arrows anyway as they tend to complicate an otherwise simple process of entering a number into a textbox.

**Comment by timotheeguerin** [comment]
This is not a material control, its our, though  the arrows are a native system implementation. We are not adding them

**Comment by ascobie** [comment]
Interesting. Though it is a material control isn't it? It's just an md input with a number type on it.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by timotheeguerin** [comment]
Nope, inputs and select are not using material anymore

**Comment by ascobie** [comment]
Not any more, but you have only just changed the controls and that hasn't been released yet. The version Bevan has will still be a material control? Or not?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by timotheeguerin** [comment]
Oh right yeah, on the picture its still the material but yeah the increase control are the same with the new input as its a native control

**Comment by ascobie** [comment]
Sweet. Ok, well as we now own the control, perhaps we could "flash" it up at bit at some stage. But it's not a priority.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by timotheeguerin** [comment]
Now that we have the new inputs those arrows are contained inside the box which makes it less confusing. Not sure this is really worth implementing or own number input for this
![image](https://user-images.githubusercontent.com/1031227/41128096-f476719a-6a61-11e8-8f4c-18c63c27ebe7.png)
