### ISSUE TITLE
Clean up RxProxy error

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#133]
Currently when requesting the contents of a file: 

https://barunneruseast2test.eastus2.batch.azure.com/jobs/..snip.../files/stdout.txt

We get an "Error in RxProxy" in the console. We keep polling for the file and so this error keeps getting logged, and logged, and logged ... 

Would be nice to kill this process if the node doesn't exist, or just keep track of the progress and only log this error once.

**Comment by timotheeguerin** [comment]
I think I fixed this when I added the breadcrumb nav https://github.com/Azure/BatchLabs/commit/233551149eeecabbd87f7fc75e8e84dbe6816b48#diff-7cbba98f0e8faf4f713cac91449eb0ceR157
