### ISSUE TITLE
AzureBatch displaying "Python backend disconnected" on OSX

### ISSUE THREAD

**Issue by philipleaper** [Azure/BatchLabs#1331]
I am using BatchLabs to upload an Autodesk 3Ds project for remote rendering.  I have created the input filegroup and put the files there, set the scene file and set the output filegroup.  But when I click submit, it just spins.  I notice on the status bar there is a message saying "Python backend disconnected" - if I view logs I see the following:
```
{"name":"BatchLabs Python","hostname":"Phillips-MBP-2.lan","pid":1971,"level":30,"msg":"========================= STARTING PYTHON RPC SERVER PROCESS =========================","time":"2018-05-08T11:11:27.405Z","v":0}
{"name":"BatchLabs Python","hostname":"Phillips-MBP-2.lan","pid":1971,"level":50,"msg":"/private/var/folders/bz/vsvcxypj70n3st89gsxhfny00000gn/T/AppTranslocation/5368E58D-A7A3-43AF-8D82-9034B05D6C7E/d/BatchLabs.app/Contents/Resources/python-rpc/main: /private/var/folders/bz/vsvcxypj70n3st89gsxhfny00000gn/T/AppTranslocation/5368E58D-A7A3-43AF-8D82-9034B05D6C7E/d/BatchLabs.app/Contents/Resources/python-rpc/main: cannot execute binary file\n","time":"2018-05-08T11:11:27.409Z","v":0}
```
I have both python 2.7.14 and python 3 installed.  2.7 appears to be the default on the PATH (as that's what runs when I run 'python' from anywhere).

The version of BatchLabs I'm using is "Version 0.15.0 (0.15.0.050118.0001)"

**Logs, for bugs(Click profile > View Logs > app.log, client.log)**

The following are the contents of the logs:

app.log:
```
{"name":"BatchLabs Renderer","hostname":"Phillips-MBP-2.lan","pid":1971,"level":30,"msg":"Websocket connection closed. Retrying to connect in 524288s","time":"2018-05-08T11:11:27.416Z","v":0}
```
client.log:
```
{"name":"BatchLabs Main","hostname":"Phillips-MBP-2.lan","pid":1971,"level":30,"msg":"Stopping python rpc server!","time":"2018-05-08T11:11:27.396Z","v":0}
{"name":"BatchLabs Main","hostname":"Phillips-MBP-2.lan","pid":1971,"level":30,"msg":"Python path is: '/private/var/folders/bz/vsvcxypj70n3st89gsxhfny00000gn/T/AppTranslocation/5368E58D-A7A3-43AF-8D82-9034B05D6C7E/d/BatchLabs.app/Contents/Resources/python-rpc/main', Args: 45032","time":"2018-05-08T11:11:27.397Z","v":0}
{"name":"BatchLabs Main","hostname":"Phillips-MBP-2.lan","pid":1971,"level":30,"msg":"Python Rpc server started!","time":"2018-05-08T11:11:27.405Z","v":0}
{"name":"BatchLabs Main","hostname":"Phillips-MBP-2.lan","pid":1971,"level":50,"error":126,"msg":"Python Rpc server has exited unexpectedly with code!","time":"2018-05-08T11:11:27.410Z","v":0}
```
python server.log:
```
{"name":"BatchLabs Python","hostname":"Phillips-MBP-2.lan","pid":1971,"level":30,"msg":"========================= STARTING PYTHON RPC SERVER PROCESS =========================","time":"2018-05-08T11:11:27.405Z","v":0}
{"name":"BatchLabs Python","hostname":"Phillips-MBP-2.lan","pid":1971,"level":50,"msg":"/private/var/folders/bz/vsvcxypj70n3st89gsxhfny00000gn/T/AppTranslocation/5368E58D-A7A3-43AF-8D82-9034B05D6C7E/d/BatchLabs.app/Contents/Resources/python-rpc/main: /private/var/folders/bz/vsvcxypj70n3st89gsxhfny00000gn/T/AppTranslocation/5368E58D-A7A3-43AF-8D82-9034B05D6C7E/d/BatchLabs.app/Contents/Resources/python-rpc/main: cannot execute binary file\n","time":"2018-05-08T11:11:27.409Z","v":0}
```

If anyone could shed some light as to why the python service is not starting it would be useful.  I'm assuming the is the root cause of this issue, if this is not the case, similarly I would be keen to know.

Thanks,
Phil

**Comment by philipleaper** [comment]
FYI - Host OS is Mac (High Sierra).

**Comment by philipleaper** [comment]
Thanks for the response - I'll await any news.

**Comment by timotheeguerin** [comment]
Could you try to download this version and let me know if that works for you https://batchlabsdist.blob.core.windows.net/releases/0.15.1/BatchLabs-0.15.1-mac.zip

**Comment by philipleaper** [comment]
That seems to have done it - no message saying "python backend disconnested" and the following in the logs:

{"name":"BatchLabs Python","hostname":"Phillips-MBP-2.lan","pid":65657,"level":30,"msg":"========================= STARTING PYTHON RPC SERVER PROCESS =========================","time":"2018-05-09T12:05:04.181Z","v":0}
{"name":"BatchLabs Python","hostname":"Phillips-MBP-2.lan","pid":65676,"level":30,"msg":"========================= STARTING PYTHON RPC SERVER PROCESS =========================","time":"2018-05-09T12:05:16.135Z","v":0}

Much appreciated!

**Comment by timotheeguerin** [comment]
Release 0.15.2
