### ISSUE TITLE
Figure out why call to ratecard API is failing for pool pricing

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1333]
Call to get pool pricing info fails with this error. Will need to contact someone in that team to see what has changed.

Failed to load resource: the server responded with a status of 400 (Authentication information is not given in the correct format. Check the value of Authorization header.)

ratecard.blob.core.windows.net/ratecards/27d96b24-db2f-4847-b3a0-d556072000…S3vb5oSKy1EKYg%3D&se=2018-05-08T21%3A54%3A11Z&sp=r&rsct=application%2Fjson

**Comment by timotheeguerin** [comment]
This sounds like more of problem the rate card api is doing. We should not even have to know about this blob

**Comment by ascobie** [comment]
True, but would be good to follow up and check just to make sure. Leaving it here so we don't fopret about it. I will take a look once my current bit of work is done. Will close if there is nothing we can do.
