### ISSUE TITLE
Python server: Add more detail to error handling

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1355]
When getting an error from the CLI about failing to upload files to the file group, we are missing another nested error that contains the reason why.

Maybe we can keep looking for nested "original" objects in the error to get all of the relevant information.

![image](https://user-images.githubusercontent.com/10934358/40334005-74c140ba-5daf-11e8-80dc-175b9024aa70.png)

**Comment by timotheeguerin** [comment]
I think the main problem here is in the python server code where we should catch all error better and send them in the right format
