### ISSUE TITLE
Delete many from quick-list doesn't remove items from list

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1360]
Selecting 4 jobs in the quick-list and using the context menu to delete them, the items are deleted, but only the first one is removed from the UI. the last 3 remain: 

![image](https://user-images.githubusercontent.com/10934358/40394155-6717ced0-5e76-11e8-914f-4e88d2ac97d5.png)

Clicking refresh removes the remaining jobs.

**Edit: Same for pools.**

**Comment by timotheeguerin** [comment]
I noticed that today, it seems to be in general multi actions don't refresh all the entries

**Comment by ascobie** [comment]
Seemed to work in the Data quick-list. But deffo didn't for jobs and pools.

**Comment by timotheeguerin** [comment]
weird
