### ISSUE TITLE
After ~1 hour of intensive use, app grinds to a halt

### ISSUE THREAD

**Issue by chrisalexander** [Azure/BatchLabs#1369]
I am using v0.15.1, I think this issue was also in the previous release but I never got round to reporting it. Apologies in advance, this is just the kind of bug I wouldn't want to have submitted to my project, but I am happy to help as far as I can.

After about an hour of intensive use of the app (defined below), it eventually grinds to a halt and anything not in the window chrome (i.e. everything except the Edit View Window Environment stuff) grinds to a halt and just sits there for as long as I'm patient with it. This is admittedly not very long as I am intensively using it because I have things to do!

Intensive use of app, for me, consists of:
- Repeatedly switching between different Batch accounts
- Within each of those accounts, switching backwards and forwards between Pools and Jobs tab, and then within jobs
- Hitting the Refresh button on the Job task list pretty often
- Sometimes doing a task filter for Running or Completed (using Task Advanced Filters)
- Occasionally drilling down into a task, and then drilling down into the directories on the task node
- Occasionally scaling pools up/down

If there's any kind of logging I can turn on to help, or log files I can (privately) provide, or process diagnostics from ProcExp I can provide, please let me know what would be most useful to you. Once again apologies for the horrifically un-helpful bug report...

**Comment by chrisalexander** [comment]
Following further "intensive use", it looks like using the folder explorer to open a folder with many files in it is causing the biggest hit overall.

**Comment by timotheeguerin** [comment]
I fixed a few memory leak I found including one with the editor not being diposed correctly(Which might have been an issue when you are browsing tasks. Could you try this build and let me know if you see improvements https://ci.appveyor.com/project/azure-batch/batchlabs/build/1.0.3771/artifacts

**Comment by chrisalexander** [comment]
When I say Task view I meant when you click on a single task and it brings up the file explorer, but I also had it when you do a filter on tasks in a job as well. I will take a snapshot next time I see it. Thanks for looking at it so quickly!
