### ISSUE TITLE
Add ability to remove pinned items from drop down

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1379]
After an entity has been deleted it's no longer possible to remove it from the pinned items collection. Either add a context menu, or just a hover delete button to remove an item.

**Comment by timotheeguerin** [comment]
Let's do middle click to close and add a context menu with delete for accessibility.

Form bookmarks is using the middle click logic

**Comment by ascobie** [comment]
Cool, i also see that the form bookmarks has a delete button. Should we look to add a context menu to that as well so they are the same? or at least if we are going to have a delete button we should make it look the same as the form bookmarks.

**Comment by timotheeguerin** [comment]
Yeah we could add a context menu for bookmarks too

**Comment by ascobie** [comment]
Just so we can make sure they both look the same. Will get Nehal to change the text of the "add-pool" form so it's inline with the other text\.

![image](https://user-images.githubusercontent.com/10934358/42003629-8cbbba82-7ac0-11e8-8913-82885bc94f69.png)

**Comment by timotheeguerin** [comment]
that should be from the title of the form
