### ISSUE TITLE
Running task graph seems to be in a weird state

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1382]
The graph says i have 9 running tasks out of a possible of 7, which cant happen.

![image](https://user-images.githubusercontent.com/10934358/40630414-a3c8a11a-6326-11e8-9397-6ba5858d340c.png)

I have filtered on running tasks and there are indeed only 7 that are reported as running so i am not sure where the 9 is coming from. 

We should probably make sure that the graph cannot draw passed the limit.

**Comment by timotheeguerin** [comment]
9 is coming from the counting api. So it means it wasn't updated in time or it is inconsitent.

**Comment by ascobie** [comment]
Wondered as much. As the counting service can be quite unreliable at times, can we set the graph so that it can never draw outside the bounds of the pool? i.e. as the pool size is 7, then even if it's reporting 9 tasks running we don't overflow the graph?
