### ISSUE TITLE
Show list of account as Email or Subscription ID or AAD Name

### ISSUE THREAD

**Issue by queenofwhales** [Azure/BatchLabs#1397]
**I'm submitting a feature request

**Description**

When I use an account with Co-Administrator right to manage many other accounts, the Account lists is very hard to know which account currently working on.
![screenshot_249](https://user-images.githubusercontent.com/39660959/40824575-d2c41790-659e-11e8-906d-e8e1ce698c03.png)

Please show it like this to easy manage batch over multi account.
![screenshot_250](https://user-images.githubusercontent.com/39660959/40824817-b342f73c-659f-11e8-8acf-bdaa00619bf4.png)

**Comment by timotheeguerin** [comment]
This is a great idea. I'll look into it

**Comment by timotheeguerin** [comment]
Just to be clear on this one, it is about switch aad tenants? not subscriptions?
The problem is that batchlabs list all subscriptions across all of your tenants which is hard to find which one you want?

**Comment by queenofwhales** [comment]
When I create a new batch : 

![screenshot_251](https://user-images.githubusercontent.com/39660959/40853775-7dc1ed34-65f9-11e8-8303-afab11b5d879.png)

I can't select the right account to use that batch.

My suggestion like this : 

![screenshot_252](https://user-images.githubusercontent.com/39660959/40854357-5b4fff6e-65fb-11e8-8506-4ae008e711e9.png)


But when create new batch should only show email or AAD name
![screenshot_251](https://user-images.githubusercontent.com/39660959/40854367-61ae8448-65fb-11e8-94b4-ccf802b1f7da.png)

**Comment by timotheeguerin** [comment]
I see, wondering if the best option is to have the tenant info displayed on the side or just have a tenant picker(Similar to what the portal has).
Might be good to have a mix of both

**Comment by timotheeguerin** [comment]
Got this, this is the best I can do for now. I need to tweak the select component to be able to have a different style and make it look better which is a bigger item which I still need to figure out how to do right for performance reasons
![image](https://user-images.githubusercontent.com/1031227/40867838-4aee69a6-65bc-11e8-96e9-a5a255bcb755.png)
