### ISSUE TITLE
Task table column layout a little funky

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1422]
State column is too big.

![image](https://user-images.githubusercontent.com/10934358/41207088-a2cf7e86-6d63-11e8-8790-03de9e45c815.png)

**Edit: Filter button is also missing CSS.**

**Comment by timotheeguerin** [comment]
It is meant to be like that, I forced the time column to be a fixed size so this one strech as it now shows errors if the task has a failure info as #1410

**Comment by ascobie** [comment]
OK, fair enough re status message, but could we at least show the full title for "exit code"?

**Comment by timotheeguerin** [comment]
yeah not sure why that one is not showing correctly, might have reduced the size too much

**Comment by timotheeguerin** [comment]
oh wonder if it is because when I made it there wasn't a scrollbar
