### ISSUE TITLE
Pool from Windows managed image displays as Linux

### ISSUE THREAD

**Issue by smith1511** [Azure/BatchLabs#1436]
**Describe the bug**
When creating a Windows pool from a managed image Batch Labs seems to think its Linux.  There are places in the UI next to the pool node agent sku that show a Linux log, and when connecting to the image SSH details are generated, not RDP.

**To Reproduce**
1. Create a pool from a Windows managed image
2. Navigate to the pool details area - notice the logo by the node agent sku.
3. Also navigate to a node and click 'Connect', you'll be prompted for Linux credential input, not Windows.

**Version (please complete the following information):**
 - OS: Windows
 - Version 15.x

**Comment by timotheeguerin** [comment]
What do you mean by a managed image? Custom image?

I just checked a iaas windows server 2016 and shows alright for me
![image](https://user-images.githubusercontent.com/1031227/41478989-8ef017ae-707e-11e8-96ec-2afcc2ac0d6a.png)
