### ISSUE TITLE
Deleting 1 folder from a file group deletes ALL that match it!

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1440]
I saw this the other day and thought i was going mad, but nope, it's a bug alright. 

Given an output file group/container with the folders:

blender-tile
blender-tile1
blender-tile2
blender-tile3

If you delete "blender-tile" it will delete all 4 folders from the container that start with that one. It must be doing a delete by matching prefix or something .... I quite often name my jobs: job1, 2, 3, 4, 5, ... and so the other day i deleted one job folder and all 10 were removed.

**Comment by timotheeguerin** [comment]
Guess its because we delete by start with `[folder-name]` instead of `[folder-name]/`

**Comment by ascobie** [comment]
Yeah, dunno how I missed that initially. Whoops 😊
