### ISSUE TITLE
Transitioning a pool from fixed scaling to auto-scaling never enables the "Save" button

### ISSUE THREAD

**Issue by chrisalexander** [Azure/BatchLabs#1441]
**Describe the bug**
Transitioning a pool from fixed scaling to auto-scaling never enables the "Save" button

**To Reproduce**
1. Go to a pool that is fixed size
2. Click on the scaling icon
3. Switch tab from Fixed to Autoscale
4. Enter valid* auto-scaling formula
5. Unable to hit save button
6. Click on loads of things in various combinations, Save button still disabled

\* I set it on the Portal and it was fine

n.b. transitioning from Autoscale to Fixed is fine

**Expected behavior**
Save button enabled so you can click it to set to Autoscale.

**Screenshots**
The save button is greyed out and has a red circle with line through cursor on hover. 

**Version (please complete the following information):**
 - OS: Windows
 - Version 0.16.0-46c29a2f

**Comment by timotheeguerin** [comment]
Hhm I am unable to repro this one, can you share some screenshot of both tabs?

**Comment by chrisalexander** [comment]
![image](https://user-images.githubusercontent.com/50909/41545770-df33bfe4-7313-11e8-9a73-55d897752456.png)

and

![image](https://user-images.githubusercontent.com/50909/41545875-11e41aa6-7314-11e8-9535-28201067c98d.png)

**Comment by timotheeguerin** [comment]
Ok so I think I was able to repro, are you copy & pasting a formula in there? Can you try adding a space or anything else after doing that and see if it enables? 
I get it do be disabled but it enables as soon as I modify the editor after pasting
