### ISSUE TITLE
Unable to terminate multiple tasks in a job and weird UI behavior

### ISSUE THREAD

**Issue by omartin2010** [Azure/BatchLabs#1457]
**Describe the bug**
When I terminate several tasks (57 is what I'm trying to do here), I get the confirmation to terminate tasks, and the whole windows goes dimmed.

**To Reproduce**
1. Go to a running job
2. Click on filter to get the list of tasks to appear and click on running - the list of running tasks appear)
3. Click on a task, control click on a task further in the list (I had selected 57)
4. I get the message "Are you sure your (sic) want to terminate those 57 tasks (no ?...)", and click Yes. If I instead do Delete, the screen doesn't dim, I see "Delete tasks 1/51" left over from a previous attempt, and it doesn't seem to delete them... (screen shot 3). 
5. Then the screen goes dimmed... and the tasks are not deleted... and if I drag the window to another screen, it's very weird behavior, see other screen shots. And a window with nothing inside it appears.

**Expected behavior**
It might be because my pool is being resized, but I expect it might simply show a progress bar or better yet simply send the task 

**Screenshots**
screen shot 1 : 
![batchlabs-screenshot](https://user-images.githubusercontent.com/11371870/41723424-03396ebc-7539-11e8-8731-e464c31dcdbb.png)
screen shot 2 : 
<img width="1051" alt="batchlabs-screenshot-2" src="https://user-images.githubusercontent.com/11371870/41723627-8c1bdd78-7539-11e8-857d-19adb3ebce00.png">
screen shot 3:
![batchlabs-screenshot-3](https://user-images.githubusercontent.com/11371870/41723954-6c8cf414-753a-11e8-98b9-c3497219c2a2.png)

**Logs(Click profile > View Logs > app.log, client.log)**
[client.log](https://github.com/Azure/BatchLabs/files/2123850/client.log)
[app.log](https://github.com/Azure/BatchLabs/files/2123851/app.log)

**Version (please complete the following information):**
 - OS: Windows 10 1803 17134.112
 - Version 0.16.1-d5ecce50

**Comment by timotheeguerin** [comment]
Seems to be a few 500 server error in the logs, you didnt see any error notifications?
Does the dining happens with only a few you are trying to terminate?

**Comment by omartin2010** [comment]
No messages on the screen per say. I didn’t try a lot of other combinations, but I’m happy to jump on an internal call if you wish (I’m internal, omartin) if you want to screen share and take a deeper look.

**Comment by timotheeguerin** [comment]
Sweet, will do that when I get in

**Comment by timotheeguerin** [comment]
actually nevermind I was able to repro, I'll take a look

**Comment by timotheeguerin** [comment]
Got a fix will release as 0.16.2 probably next week. If you need it immediately you can go on appveyor https://ci.appveyor.com/project/azure-batch/batchlabs and download the latest artifact of this pr(or stable when I merge)
