### ISSUE TITLE
Ability to override the BatchLabs-data  branch that we pull templates from

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#1474]
Add the ability for a user to override the branch that we use to pull the BatchLabs-data job and pool templates from. This will allow a developer to be able to define a feature branch to pull templates from as to not pollute the main master branch and potentially break templates for active users. 

Easiest place would be to add this as a user setting. Should be able to be disabled for non admin users of the app with the new workspace settings.

**Comment by timotheeguerin** [comment]
Right now you can change in the code its a variable set at the top of `ncj-template.service.ts`

```
const branch = "master";
```

**Comment by ascobie** [comment]
yeah i did see this. changing the code would risk accidentally committing this change to master, though it should get picked up. 

This case in particular, is one of our guys is only working on templates and only has BatchLabs installed, he doesn't have the codebase to edit. So allowing an end user to do this without having to change any code at all would be nice. 

There is also a work item to allow additional GitHub repo's to be used for templates, but this is a large piece of work. Figured this would be an easier change to get started.

**Comment by ascobie** [comment]
might add a new setting: 

"github.data.branch": "master"

can then be overridden.
