### ISSUE TITLE
Pool with more then 2500 nodes does not show heatmap

### ISSUE THREAD

**Issue by balteravishay** [Azure/BatchLabs#1484]
When having a pool of over 2500 nodes, the heatmap UI does not show.
instead, a blank page is shown.

**To Reproduce**
1. Scale pool to >2500 nodes.

2. In Batch labs, open the pool's heatmap page.

3. notice that the heatmap does not show.

**Expected behavior**
The same heatmap UI is shown for a larger amount of nodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/12952294/42346761-54599c58-80ac-11e8-89d3-d7ee5892e5a7.png)

**Version (please complete the following information):**
 - OS: [Osx]
 - Version 0.14.1.3221

 - OS: [Windows]
 - Version 0.16.1-d5ecce50

**Comment by timotheeguerin** [comment]
Could you share the logs? Either going on Profile > View logs or in View(in the header) > Toggle Developper Tools.

Also the heatmap is currently limited to actually exactly 2500 nodes. It will slice at 2500 and not show any more.
