### ISSUE TITLE
small issue with multi select delete

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#149]
if you click on a job, then hold down CTRL then click 2 more, it will miss the selection of the first item. Clicking on a job, then holding SHIFT then selecting another job in the list, will correctly select all the ID's, but when using CTRL, it misses the first one if you haven't held down CTRL first. 

I know it's because CTRL was not depressed when the initial job was selected, but it would seem that this would be common user practice. Select a job to delete, then decide you want to delete another one so you hold down CTRL and select the next one. But when you click on delete icon, only the ID of the second job is displayed.

A quick scan of the quicklist to decide if any more jobs are selected when you first encounter a CTRL event would do the trick.

**Comment by timotheeguerin** [comment]
yeah that sound like a bug, the active job should be selected by default I think

**Comment by timotheeguerin** [comment]
Fixed by #151
