### ISSUE TITLE
UserSubscription Batch Account Support

### ISSUE THREAD

**Issue by alfpark** [Azure/BatchLabs#239]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Description**
User Subscription Batch accounts are not supported.

**Instruction to repro the problem if applicable**
Create a User Subscription Batch account, login with AAD. Error text is:

```
AuthenticationFailed
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

AuthenticationErrorDetail: The specified type of authentication SharedKey is not allowed for this account.
```

**Comment by timotheeguerin** [comment]
Seems like the `azure-batch` SDK support AAD now so we should be able to do this.
