### ISSUE TITLE
List multi select should change color when losing focus

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchLabs#31]
Currently it looks a bit weird if you select multiple entities then click on the details for example as the selection remains the same. Should probably change to a light gray color

**Comment by theunrepentantgeek** [comment]
I'm not sure this is a bug - losing selection if/when the window loses focus might be really frustrating for users, particularly if they're using anything that grabs focus when it activates. 

Outlook used to do that in previous versions (though Outlook 2016 seems to be well behaved). Another class of products that legitimately grab focus are OOS/RSI timers that deliberately interrupt user activity.

I've checked Outlook/Word/PowerPoint/Excel (all from Office 2016) and they change the way selection is displayed when focus is lost, but don't actually unselect.

**Comment by timotheeguerin** [comment]
That would make sense, should probably think about it
