### ISSUE TITLE
List task & view files

### ISSUE THREAD

**Issue by paselem** [Azure/BatchLabs#37]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

User should be able to list and view task files

Navigate to a task - click on a "Files" tab and view a list of files associated to the task. Click on a single file should show the file in the UI as well as a download button.

**Comment by theunrepentantgeek** [comment]
Which file formats will you preview vs only download?

Obvious list includes text, csv, images. What else?

**Comment by timotheeguerin** [comment]
This can just be a list of extensions that could in the best case be customizable by the user.
