### ISSUE TITLE
UI and UX design

### ISSUE THREAD

**Issue by letmaik** [Azure/BatchLabs#370]
I'm a long-time user (well, half a year) of the [Azure Batch Explorer](https://github.com/Azure/azure-batch-samples/tree/master/CSharp/BatchExplorer) and was happy to find out about Batch Labs which will be supported and maintained in an official manner.

I ran the current master version of Batch Labs to give it a go. My impressions so far:

The good:
- I like that authentication is integrated properly now.
- I like the streaming mode of txt files on nodes, very useful for the stdout.txt / stderr.txt files. Would be even better if those two would be merged into a single stream somehow.
- I like that in general it is a bit easier to understand all the metadata, although there need to be tooltip or similar help titles and explanations.

The bad:
- Getting an overview of the state of everything, whether that's pools, tasks, or nodes, is a lot harder now. The interface seems very bloated and made "pretty" by increasing spacing, dropdown areas, separating everything in many tabs, sometimes needing vertical scrolling, etc. I have to do 10x as many clicks and scrolling compared to Azure Batch Explorer which will likely make me not use this new client in its current design.
- Lazy loading. When you have many jobs or node files then the lists only load the first 20 or so elements and when you scroll down the next bunch is lazily loaded. While this makes sense in some cases it can become a pain if you want to get a quick overview of the total state of things.

I hope this feedback helps in the further development of the tool. It will be an essential toolkit for many people and should make things as easy and painless as possible.

**Comment by timotheeguerin** [comment]
Hi, 

Thanks, for your feedback, this is great. I too agree that we could make the UI more compact to allow for a more efficient usage. 

- For the lazy loading we can't load everything as it would just lock the entire UI as Batch explorer does. What I think we could do however is provide the user with a setting to choose how many items he want to load at the same time. Would that improve your experience?
- For the layout I am just wondering if you had an example of what takes you much longer in Batch labs vs explorer. For the tabs we have it quite similar to batch explorer I feel.

**Comment by letmaik** [comment]
No, please don't introduce any settings that are not strictly necessary. It should just work by default. If a list has a million items, then let the list behave as if there are a million items, but only load the entries when scrolling to that area, see http://mleibman.github.io/SlickGrid/examples/example-optimizing-dataview.html

An example of what takes longer:
- Navigating from a task's files to the files of a task in another job. In Batch Explorer, this takes 2 clicks as the open tabs do not change. In Batch Labs it takes 6 clicks with lots of moving around.

Another thing, but this is probably on your roadmap: Making the file listing tables more nice, including sorting by columns, and displaying nicely even with very long filenames on small laptop screens.

**Comment by timotheeguerin** [comment]
That's quite interesting, however due to the azure batch service only supporting continuation token we cannot access a list at a specific point, it needs to be loaded sequentially. 

For the files I see how this can be a much more tedious. We'll see how we can improve this. Is your use case for those scenarios to have similar tasks and compare quickly their output?

**Comment by letmaik** [comment]
Maybe it's worth asking the Azure Batch guys whether they think a range access to those lists is useful and could be easily implemented. Who knows, there's a use case here already.

I think my main use case for switching between different jobs is to see the stdout/stderr, which in Batch Labs would take 4 clicks. So it wouldn't be about comparing specific task output files, and the tasks of the different jobs may be completely different. I think a simple improvement here could be to switch the tab order and make "Tasks" the default tab, and move "Configuration" to the right of that. Generally, people are more interested in the execution of things, not so much of the configuration.
