### ISSUE TITLE
Provide built app for download

### ISSUE THREAD

**Issue by probonopd** [Azure/BatchLabs#405]
Please provide the Travis CI builds for download. I am particularly interested in the [AppImage](http://appimage.org/) for Linux.

**Comment by timotheeguerin** [comment]
Thanks for your interest, this is on our backlog however sharing the output of the build require additional legal check which we are in the process of doing. This is a long process and I can't unfortunately provide any ETA either. I'll update this issue as we make progress.

But thanks for sharing AppImage this is something I was not aware of. I'll take a look.

**Comment by probonopd** [comment]
Looks like AppImage is already set up here:
https://github.com/Azure/BatchLabs/blob/6a096399625076051db3a0be03ba0253a41664bc/package.json#L79

**Comment by timotheeguerin** [comment]
Missed that, copied the build config template from somewhere. If that works it is all good.
