### ISSUE TITLE
File details page is missing the new action button formatting.

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#458]

**Comment by timotheeguerin** [comment]
fixed that on that with the different file viewer `feature/more-file-types`

**Comment by ascobie** [comment]
oh, better not complete this pull request then as i have also fixed it. How long before that branch goes in as it will be broken for users at the moment.

**Comment by timotheeguerin** [comment]
you should merge your PR actually, mine is going to take some time. I only got the images preview for now. Still need to have at least the code
