### ISSUE TITLE
Would be handle to have the ability to remove a selected storage account selection.

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#499]
To keep it inline with the portal.

**Comment by timotheeguerin** [comment]
There is actually this functionality however it seems not to show if you have no storage account in the same region as your batch account

![image](https://user-images.githubusercontent.com/1031227/27492393-ec76c758-57fa-11e7-8b23-bdae21247b18.png)

**Comment by ascobie** [comment]
i thought i had seen it somewhere ...
