### ISSUE TITLE
Clone UX for entities

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchLabs#5]
Each creatable entity should be able to be cloned from an existing.
This should just open a new create form with the input filled with the source entity values.

- [x] Clone pool
- [ ] Clone job
- [ ] Clone task

**Comment by itowlson** [comment]
If you're going to do something like this, it would be quite nice to be able to persist the clone source as a file, so I don't need to keep a pool around 'to clone from'.  These could be in the format of Azure Batch templates (aka NCJ templates) so a savvy user could easily edit and parameterise them... and longer term we would have a nice two-way story going.

**Comment by timotheeguerin** [comment]
Great idea

**Comment by paselem** [comment]
Yeah, that is a good point, but I think it's a separate feature. Supporting templates is something we should think about once we get into the NCJ like world since we will need to decide on what the serialization on disk will look like. I would actually love for these to get persisted to the batch account linked storage as a default option (if the user has one) as well as disk...

**Comment by theunrepentantgeek** [comment]
As a first cut, perhaps just allow exporting a pool/job/task to a JSON file so it can be round-tripped. Parameterization (aka ncj) could come later.

**Comment by itowlson** [comment]
@paselem Agree, templating is definitely a separate feature.  Being able to persist an object and then clone from that persisted version is I guess a halfway house, and what I was originally thinking of -- I should not have muddied the waters by mentioning parameterisation.  I can see why you might want to do cloning from an object in the account first, so you don't have to worry about a serialisation format, but being able to clone into a new account, or without keeping around a 'template' object, would for me be more useful than cloning from a live object.  Happy to take it one step at a time though, definitely!
