### ISSUE TITLE
Investigate Batch Labs web view

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#529]
Dave wonders if it would be possible to have a web view of Batch Labs.

**Comment by timotheeguerin** [comment]
This is not feasible anytime soon.
1. The batch sdk doesn't work in the browser
2. We use a bunch of electron functionalities for downloading files, context menu,etc.
3. AAD authentication is made to work with electron and will not with a web app without rewritting it
4. NCJ will not work either(without setting up a backend for it too)

**Comment by ascobie** [comment]
figured as much. he thought maybe we could have a cut down version, but i think it's not realistically doable.
