### ISSUE TITLE
Downloading an encrypted output fails

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#532]
When downloading an encrypted file from the file details page, it fails with this error: 

Uncaught exception: undefined - Hash mismatch (integrity check failed), Expected value is z78c8YIX/kb/1/tBLH743Q==, retrieved rdN0IRGTNNp5mDKFLg3aXg==.

Here is an example of an encrypted task output that you can try: 

https://andrew1973.blob.core.windows.net/public-files/100008.enc

edit: just tried ZIP files and they also failed.

**Comment by timotheeguerin** [comment]
Probably binary files
