### ISSUE TITLE
Documentation fails to mention python version 3.6 or greater is required

### ISSUE THREAD

**Issue by chrisalexander** [Azure/BatchLabs#547]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
```

**Description**
It appears Python 3.6 is required to build, however this is not mentioned in the documentation in README.md

**Instruction to repro the problem if applicable**
Follow installation instructions in README.md on completely clean VM
Errors that Python is required, and that Python 3.6 or greater is required

**Comment by timotheeguerin** [comment]
Hhm, I didn't realized it was actually breaking the build. It isn't actually required for Batchlabs to work as of now but is needed for incoming feature which should come quite soon so I'll just update the readme.
