### ISSUE TITLE
Duplicate pools in pool list after refresh

### ISSUE THREAD

**Issue by smith1511** [Azure/BatchLabs#599]
On the Pools page I see duplicate pools listed after each refresh.  It seems like the list isn't cleared before adding the new pools.  This is the NCJ branch.

![image](https://user-images.githubusercontent.com/1001494/29098257-ceec7ab4-7ce1-11e7-9497-842a569b4b2c.png)

**Comment by timotheeguerin** [comment]
Not sure how to repro this. Can you detail what steps you do? By refreshing you mean refreshing the pool list with the refresh button there?

**Comment by ascobie** [comment]
I have seen this as well. Was looking at one account, then switched to another account and i saw pools from the first, clicking on a pool would give you a 404 and then after every refresh these were duplicated again and again in the quick-list. 

I cannot repo this on demand. It only seems to happen every now and then. Though there would have no doubt been an error in the tools window, but i closed the app before i realized what was going on.

**Comment by timotheeguerin** [comment]
I think this is a side effect that happens when some other crash happens.
