### ISSUE TITLE
Graph hover text

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#608]
The hover text needs adjustment. It should say, "Task 491 started ..."

![image](https://user-images.githubusercontent.com/10934358/29149498-a691af34-7dc8-11e7-92ae-a93784879d40.png)

**Comment by timotheeguerin** [comment]
Well not sure about that it isn't the Task 491, it means here this is the 491st task to start and it happened at that time

**Comment by ascobie** [comment]
oh ok, so they are not task id's then? Do you order them by start time? That would take a while :)
In that case, just add the suffix (rd, st, nd, th) to it. That would make it easy to understand.

**Comment by timotheeguerin** [comment]
Yeah it is just sorted by start time. Same for the end time it is the nth task to complete. Performance should not be too bad. It probably takes much longer loading it from the server that sorting it. 

So yeah I can add nth
