### ISSUE TITLE
Detailed information should be shown if an error occurs during allocation

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/BatchLabs#618]
When allocating a pool, I got a good error display:

![image](https://user-images.githubusercontent.com/1272094/29345079-5a04b3ce-8290-11e7-81b4-b77ea85e884b.png)

However, this display doesn't show me the reason why the allocation failed - this is buried in the server response. Here's a screenshot of the information from Batch Explorer:

![image](https://user-images.githubusercontent.com/1272094/29345126-a9df54c6-8290-11e7-9fbc-7d6ee93fd761.png)

Ideally, this additional information would be visible in the error bar shown above. 

There's a disclosure triangle at the right of the error bar that currently doesn't show any additional information; perhaps the additional reason information could be shown when the bar is expanded.

**Comment by timotheeguerin** [comment]
hhm if you click on it doesn't it show the details under?

**Comment by theunrepentantgeek** [comment]
Toggling the disclosure triangle makes the bar taller, but has no other effect ...

![image](https://user-images.githubusercontent.com/1272094/29346046-ddb39c66-8296-11e7-80f2-1590351dc5c9.png)

Compiled from current HEAD on `master`, commit `e38c0fb`.

**Comment by timotheeguerin** [comment]
ok then it sounds like a bug

**Comment by timotheeguerin** [comment]
Can you check this is fixed in this branch `fix/pool-error-banner`

**Comment by theunrepentantgeek** [comment]
Yes, this is fixed in the branch `fix/pool-error-banner`:

![image](https://user-images.githubusercontent.com/1272094/29388179-b010ed44-8337-11e7-9516-aa5ec0e7a622.png)

Minor note - might be useful if the disclosure button was a little wider ... it's mostly hiding behind the scrollbar at present:

![image](https://user-images.githubusercontent.com/1272094/29388214-da447a90-8337-11e7-982b-89e30a98f3c9.png)

Thanks for the quick fix.

**Comment by timotheeguerin** [comment]
increased the size too

**Comment by theunrepentantgeek** [comment]
Thanks! Happy for this to be closed.
