### ISSUE TITLE
Table selection/activation improvement

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchLabs#626]
Currently if a table redirect to another url there is no way to select one or mulitple entries to perform actions.

- [x] add checkbox 
- [x] Add config to disable selection, activation, showing the checkbox

**Comment by ascobie** [comment]
yeah i was pondering this the other day as i wanted to delete file group files from the table, but any click sent you straight to the quick-list. There are many places we could add selected item actions like in application packages table.
