### ISSUE TITLE
run elevated not set when running tasks with autoUser in admin mode

### ISSUE THREAD

**Issue by xpillons** [Azure/BatchLabs#638]
Before submitting a bug please check the following:
- There is no similar bugs in the issue list.
- Make sure you used `yarn install` and NOT `npm install` when building the project

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
```

**Description**
run elevated doesn't appear to be set on the task properties even if the task is ran with autoUser scope=pool or tasks and elevationLevel=admin
This appears for a multi-instance job

**Instruction to repro the problem if applicable**
submit a task thru the CLI 2.0 with a json param file and add these 	
"userIdentity": {
		"autoUser": {
			"scope":"pool",
			"elevationLevel":"admin"
		}
	}

**Comment by timotheeguerin** [comment]
Hi, are you saying this is happening when using the azure cli or BatchLabs?

**Comment by xpillons** [comment]
This happens when you submit a job thru the CLI. BatchLabs doesn’t understand the task run in elevated mode.

**Comment by timotheeguerin** [comment]
You are right Batchlabs is still missing this functionality. I'll add an item for it. For the cli this is not exactly the right project to ask for but i'll go check if there is any known issues. https://github.com/Azure/azure-cli

**Comment by timotheeguerin** [comment]
actually never mind I understand your problem now. You are talking about the run elevated property displayed in BatchLabs? We are displaying the wrong attribute there then. Probably forgot to update  to user identity. I'll fix that.

**Comment by xpillons** [comment]
You got it ☺
