### ISSUE TITLE
Occasionally selecting a Batch account doesn't populate the jobs and pool from the selected account.

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#653]
So every now and then while navigating accounts in the dashboard you see the jobs and pools from the previously selected account. I cannot replicate this on demand unfortunately.

The jobs and pools below do not belong to my "andrew1973" account. The application packages do.

![issue](https://user-images.githubusercontent.com/10934358/29903941-91000ea2-8e5a-11e7-85a6-270cf57a8195.jpg)

**Comment by ascobie** [comment]
I can now reproduce the issue where one account shows the data from another.

Go to mayatest account
Click on pools
Click on dashboard

While this is still loading and as quick as possible, click on the favorite account selector and select Andrew1973.

Andrew1973 will then show the data from mayatest.

This will be inherently difficult to fix, though will affect MS employees more than end-users due to the number of accounts MS employees have access to and will be more likely to be swapping accounts.

**Comment by ascobie** [comment]
This doesn't seem to be happening any more, has it been fixed?

**Comment by timotheeguerin** [comment]
Yeah I might have fixed that part of another issue. Tried again to repro and it doesn't seem to happen anymore. I'll close for now, repopen if it happens again
