### ISSUE TITLE
Profile menu item forces navigation to dashboard and reload when closed.

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#660]
When i click on the new "Profile" nav item i see a context menu. When i click away from the menu without selecting anything the dashboard reloads. 

If i am on any other section of the application and i do the same (click and then close), it navigates me back to the dashboard and reloads the window automatically.

**Comment by timotheeguerin** [comment]
I think I forgot to remove a routerlink which probably points to the root and so goes to the dashboard
