### ISSUE TITLE
3dsmax Batch labs foreign characters.

### ISSUE THREAD

**Issue by matthew-rollitt** [Azure/BatchLabs#667]
**Description**

**Instruction to repro the problem if applicable**

I’ve created a pool batchlabspool and ran a 3dsmax job. If I view the file stdout.txt in batchLabs every character is unreadable.  
After downloading the stdout.txt and having a closer look at the file contents I noticed it contains few Chinese characters at the end of the file, I believe this is causing the issue. 

“9/6/2017 1:45:00 AM;  Scene <D:\batch\tasks\workitems\3dsmax-render3\job-1\jobpreparation\wd\assets\Cloud Render Test.max> completed.
潤敮਍ “
![image](https://user-images.githubusercontent.com/1754889/30093456-90a4d7f8-9319-11e7-8dbd-6b6aab4c53df.png)

**Comment by timotheeguerin** [comment]
This seems to show the same weird characters in between letters in sublime text and vscode so I guess this is just a problem with 3ds max output 
![image](https://user-images.githubusercontent.com/1031227/30122441-49b7432a-92e3-11e7-8f88-c4266c796f1c.png)
