### ISSUE TITLE
Should be able to Add a task using the button bar

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/BatchLabs#688]
A button to add a new task should be included on the button bar just above the list of tasks, next to "expand" and "refresh".

When you're viewing a list of pools, you can add a new pool by pressing `+` on the button bar at the top of the list:
![image](https://user-images.githubusercontent.com/1272094/30349625-b3513a82-9867-11e7-823d-6e9c375e57f0.png)

When you're viewing a list of jobs, you can add a new job by pressing `+` on the button bar at the top of the list:

![image](https://user-images.githubusercontent.com/1272094/30349673-d811ddc2-9867-11e7-8a47-148414766f45.png)

When you're viewing a list of tasks, you **should** be able to add a new task by pressing `+` on the button bar at the top of the list (but you currently cannot):

![image](https://user-images.githubusercontent.com/1272094/30349717-fcbe568c-9867-11e7-9f28-fc898175b0bb.png)

**Comment by ascobie** [comment]
you can add a task from the quick-list, or from the job details card. 

![capture](https://user-images.githubusercontent.com/10934358/32707268-7b636a50-c887-11e7-8aca-30c0a50eaf94.PNG)

or from here: 

![capture2](https://user-images.githubusercontent.com/10934358/32707272-7f43fc8e-c887-11e7-9c10-4a6ce7c7c7bd.PNG)

**Comment by theunrepentantgeek** [comment]
An offline chat with @ascobie has convinced me that this isn't needed.
