### ISSUE TITLE
Misleading message "The files for the specified task have been cleaned from the node."

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/BatchLabs#689]
When selecting a task that has never run - it's still pending execution - the *Log Output* tab shows the message "The files for the specified task have been cleaned from the node."

Since the task hasn't yet been scheduled, this message is misleading.

![image](https://user-images.githubusercontent.com/1272094/30350059-4f667c6a-9869-11e7-9813-33dd8af0b37c.png)

To reproduce:

* Create a pool with no nodes (so nothing will run)
* Create a job on that pool
* Create a new task within that job
* Select the task and switch to the *Log Output* tab if it is not already showing

**Comment by timotheeguerin** [comment]
Yes noticed that too, I am planning to move that UI inside the new task output file explorer anyway so that will be part of the move. Will come with #655
