### ISSUE TITLE
Suggest using iconography instead of a label for the breadcrumb bar

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/BatchLabs#696]
Instead of using a sub-scripted *type* label in the breadcrumb bar, use an icon that identifies the type of the item.

For example, instead of showing the pool _scratchlinux_ like this:
![image](https://user-images.githubusercontent.com/1272094/30358642-f442ed10-9899-11e7-82d8-1f5f5eec432e.png)

You could reuse the pool icon and display it like this:
![image](https://user-images.githubusercontent.com/1272094/30358653-ff785c92-9899-11e7-9626-a442d3324656.png)

It's still obvious that this is a pool - both the proximity to the label "Pools" and the reuse of the pool icon do this. Also the advantage of keeping the text baseline level across items, avoiding the visual jar that occurs currently.

You could make the same change for jobs - from this example:
![image](https://user-images.githubusercontent.com/1272094/30358678-27816396-989a-11e7-9e11-0cda3f9cb344.png)

To this mockup:
![image](https://user-images.githubusercontent.com/1272094/30358681-2caf9432-989a-11e7-8d24-6ba3192cc14e.png)

**Comment by timotheeguerin** [comment]
sounds like a good idea
