### ISSUE TITLE
Heatmap v1

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#70]
Add a heatmap to the pool UI.

Work in [feature/heatmap](/Azure/BatchLabs/tree/feature/heatmap)

**Comment by ascobie** [comment]
I think it might be a little more important than a "nice to have". It's pretty much the number 1 thing people have been waiting for in the portal and the most used aspect of Batch Explorer. 

I would up the priority.

**Comment by timotheeguerin** [comment]
Should use [d3.js](https://d3js.org/) instead of canvas
