### ISSUE TITLE
Show current quota usage on the account page

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchLabs#799]
List all the pools and sum the number of cores to get the current number of cores used for the account to see if reaching the maximum soon

**Comment by johnnyzhang82** [comment]
Here is what I sketched for pool usage, core quotas, and there are 3 different states of each progress
Todo: Job quota

| Value range  | Color |
| ------------- | ------------- |
| x >= 90% | Red (Error color)|
| 50% < x < 90%| Orange(warn color)|
| x <= 50% | Green(success color)|

![image](https://user-images.githubusercontent.com/26984399/33746036-533b7950-db6f-11e7-89a3-685c22a34a86.png)

**Comment by timotheeguerin** [comment]
Looks good il would maybe make the progress a bit thinner and try to touch the bottom of the tile
