### ISSUE TITLE
Nav/UX could be improved when account added (and no account selected)

### ISSUE THREAD

**Issue by davefellows** [Azure/BatchLabs#8]
**Description**
If you add a new account, then click it in the left pane, and then click Jobs or Pools on the left nav rather than in the main area, nothing shows in the main area, as it appears the account hasn't been 'selected'.

I would suggest two changes;
1. Clicking the newly added account in the left pane should activate it.
2. If there's no active account selected then the left nav should be disabled (it wasn't super obvious the issue was due to the account still not being activated/selected as the warning is small and on the other side of the screen).

**Comment by timotheeguerin** [comment]
So when you add an account for he first time it should be automatically selected if it doesn't this is a bug. Are you saying that when you select an account on the left it should keep it the selected account?  or that there was no account selected at all?
