### ISSUE TITLE
Failed to upload file groups for classic storage accounts

### ISSUE THREAD

**Issue by brnleehng** [Azure/BatchLabs#819]
**Description**
In our docs for [Batch Rendering Services](https://docs.microsoft.com/en-us/azure/batch/batch-rendering-service#options-for-provisioning-required-applications), we require an Azure storage account. However, only ARM storage accounts works with the file upload. 

Is this a bug? Or is classic storage accounts do not work with the Gallery feature? If so, we should add documentation to only use ARM storage accounts.

**Instruction to repro the problem if applicable**
1) Create a classic storage account
2) Link it to your Batch Account
3) Follow the 3DS BatchLabs-Data Tutorial (https://github.com/Azure/BatchLabs-data/tree/master/ncj/3dsmax): This will fail on uploading file groups

![failed_upload](https://user-images.githubusercontent.com/5770004/32235288-478b8bd8-be1c-11e7-99d4-a945863a2177.png)

**Comment by timotheeguerin** [comment]
Hhm, nice catch, I think the problem is then in the batch cli extensions. We should see if classic can be supported otherwise we should disable the feature in batchlabs when using a classic.

**Comment by ascobie** [comment]
Classic storage accounts are not supported by the CLI. This caught me out as well so i upgraded my storage account and it works now. If you try and run a command manually against the CLI with a classic account it will fail with the "not supported" error.
