### ISSUE TITLE
Allow user to download a folder from within a file group.

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#827]
Using NCJ templates, users upload outputs to either the input file group or a separate one for outputs. This may or not container more than just the output images. 

Currently you can only download the entire file group, allowing the download of a single folder would make this a better experience. 

Also, we need to display better download progress to the user. "10/100 files downloaded - 10%" ...

**Comment by timotheeguerin** [comment]
duplicate of #657
