### ISSUE TITLE
Improve experience for finding failed task

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchLabs#829]
A failed task is a task with a failure info but there is no failureInfo Odata filter so we can't do a server side list. Might be a way to find it.

**Comment by ascobie** [comment]
Would not get scheduling errors but could list: 

executionInfo/exitCode ne 0 and state eq 'Completed'

**Comment by timotheeguerin** [comment]
you can already do that one, the problem is when the task succeed but the file upload doesn't then there is a failureInfo but the exitCode is still 0

**Comment by wintersteiger** [comment]
The color of tasks in the task list is not very helpful at all. I routinely run jobs with hundreds of thousands of tasks and once in a while a few of them fail, but I have no way to find them in any of the task lists. 

For example: 
![image](https://user-images.githubusercontent.com/10155819/42411146-ced726ba-81ee-11e8-816d-1835a9083d4e.png). 

I need a list of exactly those 121 tasks and nothing else.

**Comment by timotheeguerin** [comment]
Good news is that this filter is being worked on right now. I can't give a exact ETA but you should see that coming in the next few months(With the next api version probably)
