### ISSUE TITLE
Make notification stay longer on the screen

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#848]
Notification disapear a bit too fast when they have actions.

**Comment by timotheeguerin** [comment]
it should go in the notification tray and you should still see it there after, doesn't it?

**Comment by ascobie** [comment]
Oh, so it does ... OK then, if we can maybe show the notification for a little longer then cool, but otherwise we can just close this issue.

**Comment by timotheeguerin** [comment]
we can change all the notification to be a bit longer I feel like just changing one makes it inconsistent

**Comment by timotheeguerin** [comment]
Or maybe only if the notification has an action?

**Comment by ascobie** [comment]
Yip, that sounds like a good idea. Just long enough to read it and click on it should you want to.
