### ISSUE TITLE
Support command line parameters to support custom workflow

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#856]
There was a discussion on emails over the weekend about supporting command line parameters, so we can have customized workflows for various NCJ related features. I have included the basic conversation flow from the emails, with any external names and companies removed:

[conversation.docx](https://github.com/Azure/BatchLabs/files/1465259/conversation.docx)

I looked into passing parameters into the exe. It looks like we could pass them into the application from here"

`const batchLabsApp = new BatchLabsApplication(autoUpdater, process.argv);`

Which could in turn pass off to a command line launcher to set up the state of the application and any behind the scenes actions.

The main premise seemed to be, pass in as much information as required to automatically upload any required assets and submit a job on behalf of the user. Then to automatically redirect to the job details UI.

We could log any dynamic workflow like so:

BatchLabs started with create job request
Parameter validation OK
Discovering assets ... 
Uploading 10/100 assets (10%)
Uploading 11/100 assets (11%)
Submitting job '<jobid>' with auto-pool
Job submission complete
Launching job details view for job: '<jobid>'

**Comment by ascobie** [comment]
After talking with Dave, rather than fully automated job submission as outlined above, we pre-populate all the relevant fields/info so the user can refine before uploading and submitting. 

For asset uploads, we could have a new template section that you can use an existing file group or enter the name of a new one, select the directories you want to upload, your main job asset file, then click create and it will upload it for you.

**Comment by timotheeguerin** [comment]
I think for this one actually we should go more towards this using links and custom protocol #934
That way you don't need to know where batchlabs is installed or have it available in the path.

**Comment by ascobie** [comment]
Closing as have just implemented setting up a NCJ job template via the protocol handler.
