### ISSUE TITLE
Missing SKU details about Linux N series VM

### ISSUE THREAD

**Issue by ascobie** [Azure/BatchLabs#872]
![capture](https://user-images.githubusercontent.com/10934358/32917849-56c40ab4-cb85-11e7-8219-b4ff12bbc7b9.PNG)

**Comment by timotheeguerin** [comment]
This should not have anything to do with the vm size this is the os which is not displayed correcly. What is the OS config?

**Comment by ascobie** [comment]
True, let me find the pool again ....
