### ISSUE TITLE
Data upload in file group is not working

### ISSUE THREAD

**Issue by jjindrich** [Azure/BatchLabs#912]
I'm creating new file group and trying to upload data. Not working - Never ending upload process

**Comment by timotheeguerin** [comment]
Hi, 
Can you check the logs. If you are using the latest batchlabs you should have a link to the logs folder by clicking on the profile icon then view logs. Otherwise ctrl+shift+i should show the console. Is there any error there?
Also what OS are you running batchlabs on?

**Comment by jjindrich** [comment]
Using Windows version primary, but tested on Linux too. Log file report Websocket connection closed. FW disabled, tested on different networks...
Version 0.8.0 is working correctly.

**Comment by timotheeguerin** [comment]
I think I found the issue, the python executable builder version wasn't locked and the latest seems to have a bug which our latest build would have used. 
We were planning to do a new release today so I'll double check this fix the problem.

Can you also confirm this is the error you see in the `python-server.log` file in the logs folder

`Fatal Python error: Py_Initialize: unable to load the file system codec`
