### ISSUE TITLE
VM Size selector broken (v10.1)

### ISSUE THREAD

**Issue by psyrus** [Azure/BatchLabs#940]
In version 10.1 it is not possible to select a VM size properly unless it is directly from the General Purpose tab. Switching tabs will break the VM list display completely (goes out of frame). If the user selects another tab and returns to the General Purpose tab, it will also be broken. This was not present in v9. 

**Instruction to repro the problem if applicable**
1. Manually create a pool
2. Select an OS
3. On step 4 (Choose a virtual machine size), select any tab other than "General Purpose" and the UI for VM size should break

Video can be seen here:
https://www.youtube.com/watch?v=M6Jrr8URSgk

**Comment by timotheeguerin** [comment]
thanks for the report, I have a fix out, I'll start to deploy 0.10.2 very soon
