### ISSUE TITLE
ghost box in version 0.10.1

### ISSUE THREAD

**Issue by mkiernan** [Azure/BatchLabs#945]
Before submitting a bug please check the following:
- There is no similar bugs in the issue list.
- Make sure you used `yarn install` and NOT `npm install` when building the project

**I'm submitting a ...**  (check one with "x")
```
[* ] bug report
[ ] feature request
```

**Description**
I just upgraded to version 0.10.1, and it shows this ghost box:

![image](https://user-images.githubusercontent.com/24193619/33514704-2816d1b2-d772-11e7-90b1-76689d0b12f1.png)

I guess perhaps a login screen that is not working for some reason.

**Comment by timotheeguerin** [comment]
Does this happens everytime you start the app? Could you check the logs to see if there is any errors: `Profile > View Logs > client.log/app.log` or `ctrl+shift+i` to view the console.
