### ISSUE TITLE
BatchAI Support?

### ISSUE THREAD

**Issue by mkiernan** [Azure/BatchLabs#946]
Are there any plans to provide BatchAI support in Batch Labs ?  Would be nice to be able to present a consistent view of Batch platforms, including Batch AI.

**Comment by timotheeguerin** [comment]
we are still discussing what is the spot of Batch AI in Batchlabs and if we should include it at all.

**Comment by paselem** [comment]
There are no plans to support Batch AI in Batch Labs. Maybe have a separate UI for it altogether. Still very early panning. Closing.
