### ISSUE TITLE
Shortcut "cmd+H" is not supported on macOS

### ISSUE THREAD

**Issue by vejuhust** [Azure/BatchLabs#948]
**Description**
Almost every app on macOS supports shortcut "cmd+H" to hide the window, but Batch Labs doesn't.

**Instruction to repro the problem if applicable**

Press "cmd+H" when Batch Labs window is active and nothing happens.

**Comment by timotheeguerin** [comment]
Cool didn't knew about this shortcut being standard. I'll take a look at it. If there is any other missing let us know
