### ISSUE TITLE
ResourceFiles component of job template is still limited to ~32k characters

### ISSUE THREAD

**Issue by psyrus** [Azure/BatchLabs#978]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Description**
This issue was solved in the Maya Batch Rendering plugin, and I thought it was addressed in issue #757 , but today when submitting a 3ds Max & V-ray scene today that has many scene files due to being part of a tutorial set, due to the way that filegroups work (parent directory selection), all 100+ files (and 10+ subfolders) were included despite only about 8 files (scene file + asset files) being actually used in the render. 

In cases like this, it seems that the character limitation issue still shows up. 
<img width="751" alt="batchlabs-resourcefiles-length" src="https://user-images.githubusercontent.com/8152287/33927323-276da11c-e025-11e7-8808-e873c3e7db75.png">

**Comment by psyrus** [comment]
Ah, looking through the pull request (https://github.com/Azure/BatchLabs/pull/911), it seems like an actual special submission template has been created for these situations. (V-ray CPU xxx with SAS). I'll go test that template now.

**Comment by psyrus** [comment]
I tried to run a job with the SAS based templates but there were two issues:

1. There is no SAS option with MXP file that I could find
2. The filegroup upload hangs when adding the files. 

I have uploaded a video of what I saw when trying it:
https://www.youtube.com/watch?v=UT5PznIok-A

**Comment by ascobie** [comment]
Hi Trevor, 

The current version of BatchLabs (0.10.2) does not have the SAS token generator pull request included. Tim is currently generating version 11.0 of BatchLabs which will include it. It should be available in a day or 2. Should you like to try it sooner you can pull the master branch and run "npm run build-and-pack" which will create an installer for the current master branch.

i will look into the other issue. can you get any error logs, from either the console (CTRL + Shift + i), or from the logs directory: 

![capture](https://user-images.githubusercontent.com/10934358/33930380-9133d586-e051-11e7-8c33-7810dae1e953.PNG)

**Comment by psyrus** [comment]
Hi Andrew,

Thanks for the info! That makes sense if the fix hasn't been integrated into the current version. 

I have attached my logs here:
[logs.zip](https://github.com/Azure/BatchLabs/files/1554847/logs.zip)

The upload error seems to have been some kind of timeout waiting for a websocket, but I didn't get the same error with the regular V-ray CPU templates.

**Comment by ascobie** [comment]
With regards to the upload issue. It looks like a previous upload had either failed or was taking a long time to complete as there was still something being uploaded when you tried to create the new file-group. Next time this happens please check the logs/console and that will tell us what went wrong. Chances are any subsequent upload attempt will fail also if there was a previous failure.

Also, it does seem like you have a LOT of file groups, there is basically no limit, but you can delete old ones from the "Data" menu to make it easier for you.

**Comment by ascobie** [comment]
Hi Trevor, that ZIP file is empty.

**Comment by psyrus** [comment]
Hi Andrew, sorry about that, no idea why 7zip decided to make an empty zip file, but this one should have the proper ones in there
[logs.zip](https://github.com/Azure/BatchLabs/files/1554882/logs.zip)

**Comment by psyrus** [comment]
> Also, it does seem like you have a LOT of file groups, there is basically no limit, but you can delete old ones from the "Data" menu to make it easier for you.

Yeah unfortunately we use the same batch account for both the Maya plugin testing as well as batch labs... and the maya plugin creates a new FG per render 😆 They do build up quickly!

**Comment by timotheeguerin** [comment]
Yeah so I wonder if submitting that >32k resource files killed the connection. Version 0.11.0 should allow you to restart the server in case it crashed. I'll take a look at if invalid params makes it crash
