### ISSUE TITLE
Should disable "add a pool button" before vmSize is initialized

### ISSUE THREAD

**Issue by johnnyzhang82** [Azure/BatchLabs#985]
Clicked 'add a pool' right after ctrl + shift + R (less in 3 sec) will get console error.
Should disable this button until dependencies are loaded.

![image](https://user-images.githubusercontent.com/26984399/34134421-57463b40-e40f-11e7-89da-cec3acd68c09.png)

**Comment by timotheeguerin** [comment]
Don't think we should disable it but we should handle the fact it is not loaded yet.
If its disabled it might be quite confusing if the loading takes a while for some reason
